//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicDOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreement
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int CompanyId { get; set; }
        public int PayrollId { get; set; }
        public double RateEmployees { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Company Company { get; set; }
        public virtual Payroll Payroll { get; set; }
    }
}
