//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicDOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Sequence = 1;
            this.Enabled = true;
            this.Agreement = new HashSet<Agreement>();
            this.ServiceLog = new HashSet<ServiceLog>();
            this.PatientAccounts = new HashSet<PatientAccount>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string RecipientID { get; set; }
        public string PatientAccount { get; set; }
        public int ReleaseInformationId { get; set; }
        public string ReferringProvider { get; set; }
        public string AuthorizationNUmber { get; set; }
        public int Sequence { get; set; }
        public int DiagnosisId { get; set; }
        public bool Enabled { get; set; }
        public int WeeklyApprovedRBT { get; set; }
        public int WeeklyApprovedAnalyst { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agreement> Agreement { get; set; }
        public virtual ReleaseInformation ReleaseInformation { get; set; }
        public virtual Diagnosis Diagnosis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceLog> ServiceLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAccount> PatientAccounts { get; set; }
    }
}
